/***************************************************************************;
** PROGRAM TITLE     : 
** PROGRAM LOCATION  : 
** SAS VERSION	     : 9.3
****************************************************************************;
**PROGRAM DESCRIPTION:	
	- 
****************************************************************************;
** ORIGINAL INPUT FILES:

** OUTPUT FILES:
** RELEVANT SOURCE(S): 
	- 	  
****************************************************************************;
** CREATED BY / DATE : P. Lee <DATE>
** AUDITED BY / DATE : 	

** UPDATED BY / DATE :
** UPDATE EXPLANATION : 
** AUDITED BY / DATE :
****************************************************************************/


proc datasets lib=work nolist kill; quit;  *gets rid of everything in Work library;
options compress=no mprint nolabel spool mlogic;
dm "log; 'clear'; output; 'clear'";

**********************
options 
   mprint  /*displays the SAS statements that are generated by macro execution. The SAS statements are useful for debugging macros*/
   compress=no  /*specifies that the observations in a newly created SAS data set are uncompressed (fixed-length records).*/
   nolabel; /*specifies that SAS procedures cannot use labels with variables. If NOLABEL is specified, the LABEL option of a procedure is ignored.*/
   dm /*stands for Display Manager*/
/********************/


libname libname1 "path1";

*%let path="path1";


**************************************************
START PROGRAM HERE!
**************************************************;

data import_sba;
	infile "C:\Users\pejhlee\Downloads\SBA_Loan_data_.csv" delimiter = ',' firstobs=2 missover dsd lrecl=50000;

	informat
		program      		    $3.
		borrname      			$30.
		borrstreet  		    $29.
		borrcity				$30.
		borrstate				$2.
		borrzip					$5.
		cdc_name				$30.
		cdc_street				$30.
		cdc_city				$16.
		cdc_state				$2.
		cdc_zip					$5.
		tplender_name			$30.
		tplender_city			$25.
		tplender_state			$2.
		tpdollars				10.
		grossapproval			7.
		approval_date			5.
		approval_fyear			4.
		delivery_method			$7.
		subpgmdesc				$52.
		init_intrate			best8.
		term_months				3.
		naics_code				$6.
		naics_desc				$75.
		project_county			$21.
		project_state			$2.
		business_type			$11.
		loan_status				$6.
		chargeoff_date			5.
		gross_chargeoff_amt		9.
	;

	input
		program      		    $
		borrname      			$
		borrstreet  		    $
		borrcity				$
		borrstate				$
		borrzip					$
		cdc_name				$
		cdc_street				$
		cdc_city				$
		cdc_state				$
		cdc_zip					$
		tplender_name			$
		tplender_city			$
		tplender_state			$
		tpdollars				
		grossapproval			
		approval_date			
		approval_fyear			
		delivery_method			$
		subpgmdesc				$
		init_intrate			
		term_months				
		naics_code				$
		naics_desc				$
		project_county			$
		project_state			$
		business_type			$
		loan_status				$
		chargeoff_date			
		gross_chargeoff_amt		
	;

	format
		program      		    $3.
		borrname      			$30.
		borrstreet  		    $29.
		borrcity				$30.
		borrstate				$2.
		borrzip					$5.
		cdc_name				$30.
		cdc_street				$30.
		cdc_city				$16.
		cdc_state				$2.
		cdc_zip					$5.
		tplender_name			$30.
		tplender_city			$25.
		tplender_state			$2.
		tpdollars				10.
		grossapproval			7.
		approval_date			mmddyy10.
		approval_fyear			4.
		delivery_method			$7.
		subpgmdesc				$52.
		init_intrate			best8.
		term_months				3.
		naics_code				$6.
		naics_desc				$75.
		project_county			$21.
		project_state			$2.
		business_type			$11.
		loan_status				$6.
		chargeoff_date			mmddyy10.
		gross_chargeoff_amt		9.
	;

run;

data clean_sba;
	set import_sba;

** upcasing all the char. variables;
%macro upper(var);
	&var = upcase(&var);
%mend upper;
%upper (borrname);
%upper (borrstreet);
%upper (borrcity);
%upper (borrstate);
%upper (cdc_name);
%upper (cdc_street);
%upper (cdc_city);
%upper (cdc_state);
%upper (tplender_name);
%upper (tplender_city);
%upper (tplender_state);
%upper (delivery_method);
%upper (subpgmdesc);
%upper (naics_desc);
%upper (project_county);
%upper (project_state);
%upper (business_type);
%upper (loan_status);

** fixing date formatting from excel to sas;
	approval_date = approval_date - 21916;
	chargeoff_date = chargeoff_date - 21916;


run;

data clean_sba2;
	set clean_sba;
	** remove loans with blank loan status or CANCLED loan status from dataset (on piazza);
	if loan_status ~= '';
	if loan_status ~= 'CANCLD';
run;
